//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroMobileApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EuroMobileApp.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account already exists for this account type.
        /// </summary>
        internal static string AccountAlreadyExists {
            get {
                return ResourceManager.GetString("AccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No activities found!.
        /// </summary>
        internal static string ActivityLogTitle {
            get {
                return ResourceManager.GetString("ActivityLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddButtonText {
            get {
                return ResourceManager.GetString("AddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string AddNewButtonLabel {
            get {
                return ResourceManager.GetString("AddNewButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Date/Time.
        /// </summary>
        internal static string AppDateTime {
            get {
                return ResourceManager.GetString("AppDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliance.
        /// </summary>
        internal static string ApplianceLabel {
            get {
                return ResourceManager.GetString("ApplianceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Of Appliance.
        /// </summary>
        internal static string AppliancePlaceHolder {
            get {
                return ResourceManager.GetString("AppliancePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select appliance type.
        /// </summary>
        internal static string ApplianceRequired {
            get {
                return ResourceManager.GetString("ApplianceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliance.
        /// </summary>
        internal static string ApplianceTabTitle {
            get {
                return ResourceManager.GetString("ApplianceTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to upload Image.
        /// </summary>
        internal static string ClickToUploadImage {
            get {
                return ResourceManager.GetString("ClickToUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COD/WAR.
        /// </summary>
        internal static string CODWARLable {
            get {
                return ResourceManager.GetString("CODWARLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 678910123.
        /// </summary>
        internal static string CODWARPlaceHolder {
            get {
                return ResourceManager.GetString("CODWARPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COD/WAR required.
        /// </summary>
        internal static string CODWARRequired {
            get {
                return ResourceManager.GetString("CODWARRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password.
        /// </summary>
        internal static string ConfirmPasswordAlert {
            get {
                return ResourceManager.GetString("ConfirmPasswordAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t connect to the server, please contact your system admin or try again later.
        /// </summary>
        internal static string ConnectivitySubtitle {
            get {
                return ResourceManager.GetString("ConnectivitySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity issue!.
        /// </summary>
        internal static string ConnectivityTitle {
            get {
                return ResourceManager.GetString("ConnectivityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer address.
        /// </summary>
        internal static string CustomerAddressLabel {
            get {
                return ResourceManager.GetString("CustomerAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string CustomerAddressPlaceHolder {
            get {
                return ResourceManager.GetString("CustomerAddressPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try adjusting your search or fliter to find what you&apos;re looking for.
        /// </summary>
        internal static string DefaultSubtitle {
            get {
                return ResourceManager.GetString("DefaultSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete part ?.
        /// </summary>
        internal static string DeleteWorkOrderPartConfirmAlert {
            get {
                return ResourceManager.GetString("DeleteWorkOrderPartConfirmAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string DetailsTabTitle {
            get {
                return ResourceManager.GetString("DetailsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from the network!.
        /// </summary>
        internal static string Disconnectedfromthenetwork {
            get {
                return ResourceManager.GetString("Disconnectedfromthenetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found!.
        /// </summary>
        internal static string EmptyStateDefaultTitle {
            get {
                return ResourceManager.GetString("EmptyStateDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter The Password.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EURO APPLIANCE SERVICE LTD.
        /// </summary>
        internal static string EuroApplianceServiceLtd {
            get {
                return ResourceManager.GetString("EuroApplianceServiceLtd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Go online to use this functionality!.
        /// </summary>
        internal static string GoOnline {
            get {
                return ResourceManager.GetString("GoOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login id and password.
        /// </summary>
        internal static string InvalidLoginError {
            get {
                return ResourceManager.GetString("InvalidLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Nature.
        /// </summary>
        internal static string JobNatureLabel {
            get {
                return ResourceManager.GetString("JobNatureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Nature.
        /// </summary>
        internal static string JobNaturePlaceHolder {
            get {
                return ResourceManager.GetString("JobNaturePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job nature required.
        /// </summary>
        internal static string JobNatureRequired {
            get {
                return ResourceManager.GetString("JobNatureRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Number.
        /// </summary>
        internal static string JobNumber {
            get {
                return ResourceManager.GetString("JobNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Status.
        /// </summary>
        internal static string JobStatus {
            get {
                return ResourceManager.GetString("JobStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Status.
        /// </summary>
        internal static string JobStatusLabel {
            get {
                return ResourceManager.GetString("JobStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string JobStatusPlaceHolder {
            get {
                return ResourceManager.GetString("JobStatusPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job status required.
        /// </summary>
        internal static string JobStatusRequired {
            get {
                return ResourceManager.GetString("JobStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to logout ?.
        /// </summary>
        internal static string LogOutConfirmAlert {
            get {
                return ResourceManager.GetString("LogOutConfirmAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FC AMD.
        /// </summary>
        internal static string ManufacturerPlaceHolder {
            get {
                return ResourceManager.GetString("ManufacturerPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select manufacturer.
        /// </summary>
        internal static string ManufacturerRequired {
            get {
                return ResourceManager.GetString("ManufacturerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string ManufaturerLabel {
            get {
                return ResourceManager.GetString("ManufaturerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can upload maximum 4 Image.
        /// </summary>
        internal static string MaxImageUploadAlert {
            get {
                return ResourceManager.GetString("MaxImageUploadAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage.
        /// </summary>
        internal static string MileageLabel {
            get {
                return ResourceManager.GetString("MileageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1200.
        /// </summary>
        internal static string MileagePlaceHolder {
            get {
                return ResourceManager.GetString("MileagePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage required.
        /// </summary>
        internal static string MileageRequired {
            get {
                return ResourceManager.GetString("MileageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Number.
        /// </summary>
        internal static string ModelNumberLabel {
            get {
                return ResourceManager.GetString("ModelNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter model number.
        /// </summary>
        internal static string ModelNumberRequired {
            get {
                return ResourceManager.GetString("ModelNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 56789.
        /// </summary>
        internal static string ModelPlaceHolder {
            get {
                return ResourceManager.GetString("ModelPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Orders.
        /// </summary>
        internal static string MyOrders {
            get {
                return ResourceManager.GetString("MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found.\nPlease go online to view full list..
        /// </summary>
        internal static string NoRecordsOffline {
            get {
                return ResourceManager.GetString("NoRecordsOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found..
        /// </summary>
        internal static string NoRecordsOnline {
            get {
                return ResourceManager.GetString("NoRecordsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string NoteLabel {
            get {
                return ResourceManager.GetString("NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string NotePlaceHolder {
            get {
                return ResourceManager.GetString("NotePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes required.
        /// </summary>
        internal static string NoteRequired {
            get {
                return ResourceManager.GetString("NoteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Order Found.
        /// </summary>
        internal static string NoUserOrder {
            get {
                return ResourceManager.GetString("NoUserOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, we do not have access to the INTERNET. Please connect to the Internet and try again.
        /// </summary>
        internal static string OfflineNotAvailableForResource {
            get {
                return ResourceManager.GetString("OfflineNotAvailableForResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Name.
        /// </summary>
        internal static string PartNameLabel {
            get {
                return ResourceManager.GetString("PartNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter part name.
        /// </summary>
        internal static string PartNamePlaceHolder {
            get {
                return ResourceManager.GetString("PartNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part name required.
        /// </summary>
        internal static string PartNameRequired {
            get {
                return ResourceManager.GetString("PartNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string PartNoteLabel {
            get {
                return ResourceManager.GetString("PartNoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter notes.
        /// </summary>
        internal static string PartNotePlaceHolder {
            get {
                return ResourceManager.GetString("PartNotePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes required.
        /// </summary>
        internal static string PartNoteRequired {
            get {
                return ResourceManager.GetString("PartNoteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        internal static string PartsTabTitle {
            get {
                return ResourceManager.GetString("PartsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, permission is not granted to use the media library..
        /// </summary>
        internal static string PermissionIsNotGrantedToUseMedia {
            get {
                return ResourceManager.GetString("PermissionIsNotGrantedToUseMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App needs permission to access the camera..
        /// </summary>
        internal static string Permissiontoaccessthecamera {
            get {
                return ResourceManager.GetString("Permissiontoaccessthecamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App needs permission to access the media library..
        /// </summary>
        internal static string Permissiontoaccessthemedialibrary {
            get {
                return ResourceManager.GetString("Permissiontoaccessthemedialibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App needs permission to access the phone&apos;s local storage..
        /// </summary>
        internal static string Permissiontoaccessthephonelocalstorage {
            get {
                return ResourceManager.GetString("Permissiontoaccessthephonelocalstorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string QuantityLabel {
            get {
                return ResourceManager.GetString("QuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter quantity.
        /// </summary>
        internal static string QuantityPalceHolder {
            get {
                return ResourceManager.GetString("QuantityPalceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity required.
        /// </summary>
        internal static string QuantityRequired {
            get {
                return ResourceManager.GetString("QuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate ($).
        /// </summary>
        internal static string RateLabel {
            get {
                return ResourceManager.GetString("RateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter rate.
        /// </summary>
        internal static string RatePlaceHolder {
            get {
                return ResourceManager.GetString("RatePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate required.
        /// </summary>
        internal static string RateRequired {
            get {
                return ResourceManager.GetString("RateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Option.
        /// </summary>
        internal static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        internal static string SerialNumberLabel {
            get {
                return ResourceManager.GetString("SerialNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01234.
        /// </summary>
        internal static string SerialNumberPlaceHolder {
            get {
                return ResourceManager.GetString("SerialNumberPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter serial number.
        /// </summary>
        internal static string SerialNumberRequired {
            get {
                return ResourceManager.GetString("SerialNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service date.
        /// </summary>
        internal static string ServiceDateLabel {
            get {
                return ResourceManager.GetString("ServiceDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XX-XX-XXXX.
        /// </summary>
        internal static string ServiceDatePlaceHolder {
            get {
                return ResourceManager.GetString("ServiceDatePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service date required.
        /// </summary>
        internal static string ServiceDateRequired {
            get {
                return ResourceManager.GetString("ServiceDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string ServicesTabTitle {
            get {
                return ResourceManager.GetString("ServicesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Time.
        /// </summary>
        internal static string ServiceTimeLabel {
            get {
                return ResourceManager.GetString("ServiceTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00:00 PM.
        /// </summary>
        internal static string ServiceTimePlaceHolder {
            get {
                return ResourceManager.GetString("ServiceTimePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service time required.
        /// </summary>
        internal static string ServiceTimeRequired {
            get {
                return ResourceManager.GetString("ServiceTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        internal static string TechnicianLabel {
            get {
                return ResourceManager.GetString("TechnicianLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician Name.
        /// </summary>
        internal static string TechnicianPlaceHolder {
            get {
                return ResourceManager.GetString("TechnicianPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician name required.
        /// </summary>
        internal static string TechnicianRequired {
            get {
                return ResourceManager.GetString("TechnicianRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech remarks.
        /// </summary>
        internal static string TechRemarksLabel {
            get {
                return ResourceManager.GetString("TechRemarksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter remarks.
        /// </summary>
        internal static string TechRemarksPlaceHolder {
            get {
                return ResourceManager.GetString("TechRemarksPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech remarks required.
        /// </summary>
        internal static string TechRemarksRequired {
            get {
                return ResourceManager.GetString("TechRemarksRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tect Remarks.
        /// </summary>
        internal static string TechRemarksTabTitile {
            get {
                return ResourceManager.GetString("TechRemarksTabTitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Number.
        /// </summary>
        internal static string TicketNumberLabel {
            get {
                return ResourceManager.GetString("TicketNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECE90001.
        /// </summary>
        internal static string TicketNumberPlaceHolder {
            get {
                return ResourceManager.GetString("TicketNumberPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket number required.
        /// </summary>
        internal static string TicketNumberRequired {
            get {
                return ResourceManager.GetString("TicketNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount ($).
        /// </summary>
        internal static string TotalAmountLabel {
            get {
                return ResourceManager.GetString("TotalAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter total amount.
        /// </summary>
        internal static string TotalAmountPlaceHolder {
            get {
                return ResourceManager.GetString("TotalAmountPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount required.
        /// </summary>
        internal static string TotalAmountRequired {
            get {
                return ResourceManager.GetString("TotalAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadImage.
        /// </summary>
        internal static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is required.
        /// </summary>
        internal static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password required.
        /// </summary>
        internal static string UserPasswordRequired {
            get {
                return ResourceManager.GetString("UserPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string WorkOrderFilterFirstName {
            get {
                return ResourceManager.GetString("WorkOrderFilterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string WorkOrderFilterLastName {
            get {
                return ResourceManager.GetString("WorkOrderFilterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Id.
        /// </summary>
        internal static string WorkOrderFilterWorkOrderId {
            get {
                return ResourceManager.GetString("WorkOrderFilterWorkOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Number.
        /// </summary>
        internal static string WorkOrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part deleted. Thank you.
        /// </summary>
        internal static string WorkOrderPartDeleteSuccessAlert {
            get {
                return ResourceManager.GetString("WorkOrderPartDeleteSuccessAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string WorkOrderPhoneNumber {
            get {
                return ResourceManager.GetString("WorkOrderPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order detail save successfully. Thank You.
        /// </summary>
        internal static string WorkOrderSaveAlert {
            get {
                return ResourceManager.GetString("WorkOrderSaveAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
