//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyServiceCharges
    {
        public long CompanyChargesID { get; set; }
        public Nullable<long> BillingAddressId { get; set; }
        public Nullable<long> ServiceItemID { get; set; }
        public Nullable<decimal> ServiceCharges { get; set; }
    }
}
