//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInvoiceSignatures
    {
        public long CustomerSignatureId { get; set; }
        public Nullable<long> WorkOrderId { get; set; }
        public string InvoiceSigned { get; set; }
        public string Covid_answer_1 { get; set; }
        public string Covid_answer_2 { get; set; }
        public string Covid_answer_3 { get; set; }
    }
}
