//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceItems()
        {
            this.WorkOrder_ServiceItems = new HashSet<WorkOrder_ServiceItems>();
        }
    
        public long ServiceItemID { get; set; }
        public string ServiceItem { get; set; }
        public string ServiceItemDescr { get; set; }
        public Nullable<decimal> ServicePrice { get; set; }
        public Nullable<bool> IsTaxable { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ServiceItems ServiceItems1 { get; set; }
        public virtual ServiceItems ServiceItems2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrder_ServiceItems> WorkOrder_ServiceItems { get; set; }
    }
}
