//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CustomerAppliances
    {
        public Nullable<long> ApplianceTypeId { get; set; }
        public Nullable<long> ManufacturerId { get; set; }
        public string ModelNumber { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string PNS { get; set; }
        public string Dealername { get; set; }
        public string ApplianceType { get; set; }
        public string Manufacturer { get; set; }
        public long CustomerApplianceId { get; set; }
        public Nullable<long> CustomerId { get; set; }
    }
}
