//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder_ServiceItems
    {
        public long WOServiceItems { get; set; }
        public Nullable<long> WorkOrderId { get; set; }
        public Nullable<long> ServiceItemID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ServiceNotes { get; set; }
    
        public virtual ServiceItems ServiceItems { get; set; }
        public virtual WorkOrder_ServiceItems WorkOrder_ServiceItems1 { get; set; }
        public virtual WorkOrder_ServiceItems WorkOrder_ServiceItems2 { get; set; }
    }
}
