//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder_Notes
    {
        public long WorkOrderNoteId { get; set; }
        public Nullable<long> WorkOrderId { get; set; }
        public Nullable<System.DateTime> NotesDateTime { get; set; }
        public string Notes { get; set; }
        public Nullable<int> EnteredUserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    }
}
