//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder_Parts
    {
        public long WorkOrderPartId { get; set; }
        public Nullable<long> WorkOrderId { get; set; }
        public string PartName { get; set; }
        public string PartDescription { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> InvoicePrice { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<bool> InStock { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
    }
}
