//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder_Header
    {
        public long WorkOrderId { get; set; }
        public Nullable<System.DateTime> WorkOrderDate { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> CustomerApplianceId { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public string ServiceTime { get; set; }
        public Nullable<System.DateTime> ServiceDateTime { get; set; }
        public Nullable<int> TechicianId { get; set; }
        public Nullable<int> JobNatureId { get; set; }
        public Nullable<bool> ChargeTax { get; set; }
        public Nullable<int> JobStatusId { get; set; }
        public string WorkOrderNotes { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<System.DateTime> JobCompletion { get; set; }
        public Nullable<bool> WorkOrderCancelled { get; set; }
        public string TechRemarks { get; set; }
        public Nullable<long> RecallWorkOrderId { get; set; }
        public string TicketNumber { get; set; }
        public string COD_WARN { get; set; }
        public Nullable<decimal> Mileage { get; set; }
    }
}
