//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder_Payments
    {
        public long PaymentId { get; set; }
        public Nullable<long> WorkOrderId { get; set; }
        public Nullable<long> WorkOrderLineId { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentDescription { get; set; }
        public Nullable<int> PaymentModeId { get; set; }
        public string LineType { get; set; }
    }
}
